### PR TITLE
Abstraction, change of stucture

### PR DESCRIPTION
**Pull request by MrSpaceMan1**
Abstraction over database connection, change of structure. Schemas and models are now in domain directory. #8

### CODE REVIEW

**Comment by kbojarowska** [comment]
I think that we also need an model for ingredients - they're shown in the bottom of front page

**Review by kbojarowska — CHANGES_REQUESTED** [review]
I think that we also need an model for ingredients - they're shown in the bottom of front page

**Comment by MrSpaceMan1** [comment]
> I think that we also need an model for ingredients - they're shown in the bottom of front page

Please create new issue for that

**Review by dpionk — APPROVED** [review]
LGTM

**Review by kbojarowska — APPROVED** [review]

**Pull request merged**
