### PR TITLE
Make upper part of front page

### PR DESCRIPTION
**Pull request by dpionk**
Added upper part of front page.

### CODE REVIEW

**Comment by dpionk** [comment]
fyi: I will come back to this code to correct the position of blue dots, I just want to merge the upper and bottom page to have whole front page component

**Review by MrSpaceMan1 — APPROVED** [review]

**Review by kbojarowska — CHANGES_REQUESTED** [review]
I think that the size of photos should be bigger and the gap should be smaller,
The page information text should have more width
This part should be aligned
Should be: 
image
Now it is:
image

Cofiner bush and small pink dots should be bigger

**Comment by kbojarowska** [comment]
Move images to public folder

**Comment by dpionk** [comment]
All corrected

**Review by kbojarowska — APPROVED** [review]

**Pull request merged**
